version: '3'
services:
  keycloak:
    image: jboss/keycloak:2.5.1.Final
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
    volumes:
      - ./keycloak/data:/opt/jboss/keycloak/standalone/data:rw
      - ./keycloak/log:/opt/jboss/keycloak/standalone/log:rw
    links:
      - ldap-tenant-a
      - ldap-tenant-b
  ldap-tenant-a:
    image: osixia/openldap:1.1.7
    environment:
      LDAP_ORGANISATION: 'Tenant A'
      LDAP_DOMAIN: 'a.com'
      LDAP_ADMIN_PASSWORD: 'admin'
    volumes:
      - ./tenant-a:/tmp
    #   - ./customer_a/slapd/database:/var/lib/ldap:rw
    #   - ./customer_a/slapd/config:/etc/ldap/slapd.d:rw
  ldap-tenant-b:
    image: osixia/openldap:1.1.7
    environment:
      LDAP_ORGANISATION: 'Tenant B'
      LDAP_DOMAIN: 'b.com'
      LDAP_ADMIN_PASSWORD: 'admin'
